### ISSUE TITLE
Hack is unable to properly work with Expanded Pokemon lists

### ISSUE THREAD

**Issue by Criminon** [Touched/MegaEvolution#16] opened 2015-07-08 03:35 UTC
1. Expand your pokemon list. (this step can be done before or after the hack)
2. Apply hack.
3. Notice the Lv next to the pokemon is missing while in combat.
4. Notice the hack no longer works.

**Comment by Touched** [comment] 2015-07-08 10:45
Duplicate of #14

**Closed as completed by Touched** 2015-07-08 10:45 UTC
Labels: duplicate
